safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: Deane Site
host: localhost
desc: Deane space for tech & non-tech relate

custom:
    category:
        default: Default Category
        another: Another Category
    categories:
      - name:  default
        title: Default Category

      - name:  another
        title: Another Category

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: Deane Ding
        email: deanej78@hotmail.com
        desc: Deane space for tech & non-tech relate
        disqus: disqus_pXVd6gHDfW
        gcse: 018095440609074508794:sxxvhheexek  # Google自定义搜索标识ID
        github: deanej78
        gravatar: 5e5fe7909a9cf4c30a1035c93ec11d59   # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
